//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXCTechnology.Belcorp.ePlanning.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archivo()
        {
            this.ArchivoLog = new HashSet<ArchivoLog>();
        }
    
        public long IdArchivo { get; set; }
        public string NombreCargado { get; set; }
        public string NombreHistorico { get; set; }
        public short IdPalanca { get; set; }
        public int IdCampanaPlaneacion { get; set; }
        public int IdCampanaProceso { get; set; }
        public Nullable<byte> NumeroEspacios { get; set; }
        public Nullable<byte> UnidadesLimite { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaEstado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Campana Campana { get; set; }
        public virtual Campana Campana1 { get; set; }
        public virtual EstadoArchivo EstadoArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoLog> ArchivoLog { get; set; }
    }
}
