//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXCTechnology.Belcorp.ePlanning.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ePlanningDBEntities : DbContext
    {
        public ePlanningDBEntities()
            : base("name=ePlanningDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<ArchivoLog> ArchivoLog { get; set; }
        public virtual DbSet<Campana> Campana { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Consolidado> Consolidado { get; set; }
        public virtual DbSet<Dominio> Dominio { get; set; }
        public virtual DbSet<EstadoArchivo> EstadoArchivo { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Palanca> Palanca { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<ProductoComparableAntiguo> ProductoComparableAntiguo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoOferta> TipoOferta { get; set; }
    }
}
