//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXCTechnology.Belcorp.ePlanning.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoComparableAntiguo
    {
        public byte IdPais { get; set; }
        public string CUC { get; set; }
        public string SAP { get; set; }
        public string CUCAntiguo { get; set; }
        public string SAPAntiguo { get; set; }
        public string BPCSGenericoAntiguo { get; set; }
        public string BPCSTonoAntiguo { get; set; }
        public string DescripcionGenericoAntiguo { get; set; }
        public string DescripcionTonoAntiguo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
